# ===============================================================================
# NADAKKI AI Suite - ActionPlan
# core/agents/action_plan.py
# Day 3 - Component 2 of 4
# ===============================================================================

"""
ActionPlan schema - the standardized output from every agent.

An agent receives context > consults knowledge > produces an ActionPlan.
The ActionPlanExecutor (Day 4) then executes each PlannedOperation
through the GoogleAdsConnector pipeline.

Flow:
    Agent > ActionPlan > [Human Approval if needed] > ActionPlanExecutor > Connector > Google Ads
"""

from dataclasses import dataclass, field
from datetime import datetime
from enum import Enum
from typing import Dict, List, Optional, Any
import uuid


class PlanStatus(Enum):
    DRAFT = "draft"
    PROPOSED = "proposed"
    APPROVED = "approved"
    EXECUTING = "executing"
    COMPLETED = "completed"
    FAILED = "failed"
    REJECTED = "rejected"
    PARTIALLY_COMPLETED = "partially_completed"


class OperationPriority(Enum):
    LOW = "low"
    MEDIUM = "medium"
    HIGH = "high"
    CRITICAL = "critical"


@dataclass
class PlannedOperation:
    """
    A single operation within an ActionPlan.
    
    Maps directly to an operation in the OperationRegistry.
    """
    operation_name: str             # e.g., "update_campaign_budget@v1"
    payload: Dict[str, Any]         # Arguments for the operation
    description: str = ""           # Human-readable description
    priority: OperationPriority = OperationPriority.MEDIUM
    order: int = 0                  # Execution order within the plan
    depends_on: List[str] = field(default_factory=list)  # IDs of prerequisite ops
    
    # Generated
    operation_id: str = field(default_factory=lambda: f"op_{uuid.uuid4().hex[:10]}")
    
    # Execution results (filled after execution)
    status: str = "pending"         # pending, executing, completed, failed, skipped
    result: Optional[dict] = None
    error: Optional[str] = None
    executed_at: Optional[datetime] = None
    
    def to_dict(self) -> dict:
        return {
            "operation_id": self.operation_id,
            "operation_name": self.operation_name,
            "payload": self.payload,
            "description": self.description,
            "priority": self.priority.value,
            "order": self.order,
            "depends_on": self.depends_on,
            "status": self.status,
            "result": self.result,
            "error": self.error,
            "executed_at": self.executed_at.isoformat() if self.executed_at else None,
        }


@dataclass
class ActionPlan:
    """
    Complete plan generated by an agent.
    
    Contains:
    - Strategy rationale (why these operations)
    - List of PlannedOperations (what to do)
    - Risk assessment
    - Knowledge citations (which rules were consulted)
    """
    plan_id: str = field(default_factory=lambda: f"plan_{uuid.uuid4().hex[:12]}")
    tenant_id: str = ""
    agent_name: str = ""            # Which agent created this plan
    
    # Strategy
    title: str = ""
    description: str = ""
    rationale: str = ""             # Why the agent recommends these actions
    
    # Operations
    operations: List[PlannedOperation] = field(default_factory=list)
    
    # Risk
    risk_score: float = 0.0         # 0.0 (safe) to 1.0 (high risk)
    requires_approval: bool = False
    
    # Knowledge citations
    rules_consulted: List[str] = field(default_factory=list)   # Rule IDs
    playbook_used: str = ""         # Playbook ID if following a playbook
    benchmarks_referenced: Dict[str, Any] = field(default_factory=dict)
    
    # Metadata
    status: PlanStatus = PlanStatus.DRAFT
    created_at: datetime = field(default_factory=datetime.utcnow)
    approved_at: Optional[datetime] = None
    approved_by: Optional[str] = None
    completed_at: Optional[datetime] = None
    
    # Execution summary
    total_operations: int = 0
    completed_operations: int = 0
    failed_operations: int = 0
    
    def add_operation(
        self,
        operation_name: str,
        payload: dict,
        description: str = "",
        priority: OperationPriority = OperationPriority.MEDIUM,
        depends_on: List[str] = None,
    ) -> PlannedOperation:
        """Add an operation to the plan."""
        op = PlannedOperation(
            operation_name=operation_name,
            payload=payload,
            description=description,
            priority=priority,
            order=len(self.operations),
            depends_on=depends_on or [],
        )
        self.operations.append(op)
        self.total_operations = len(self.operations)
        return op
    
    def propose(self):
        """Mark plan as proposed (ready for review)."""
        self.status = PlanStatus.PROPOSED
        # Auto-set requires_approval based on risk
        if self.risk_score > 0.5:
            self.requires_approval = True
        # Check if any operation has high-value payloads
        for op in self.operations:
            budget = op.payload.get("new_budget", 0)
            if budget > 5000:
                self.requires_approval = True
                break
    
    def approve(self, approver: str = "system"):
        """Approve the plan for execution."""
        self.status = PlanStatus.APPROVED
        self.approved_at = datetime.utcnow()
        self.approved_by = approver
    
    def reject(self, reason: str = ""):
        """Reject the plan."""
        self.status = PlanStatus.REJECTED
        self.rationale = f"REJECTED: {reason}" if reason else self.rationale
    
    def to_dict(self) -> dict:
        return {
            "plan_id": self.plan_id,
            "tenant_id": self.tenant_id,
            "agent_name": self.agent_name,
            "title": self.title,
            "description": self.description,
            "rationale": self.rationale,
            "operations": [op.to_dict() for op in self.operations],
            "risk_score": self.risk_score,
            "requires_approval": self.requires_approval,
            "rules_consulted": self.rules_consulted,
            "playbook_used": self.playbook_used,
            "benchmarks_referenced": self.benchmarks_referenced,
            "status": self.status.value,
            "created_at": self.created_at.isoformat(),
            "approved_at": self.approved_at.isoformat() if self.approved_at else None,
            "approved_by": self.approved_by,
            "completed_at": self.completed_at.isoformat() if self.completed_at else None,
            "total_operations": self.total_operations,
            "completed_operations": self.completed_operations,
            "failed_operations": self.failed_operations,
        }
    
    def summary(self) -> str:
        """Human-readable summary."""
        lines = [
            f"* ActionPlan: {self.title}",
            f"   Agent: {self.agent_name}",
            f"   Status: {self.status.value}",
            f"   Risk: {self.risk_score:.1%}",
            f"   Operations: {self.total_operations}",
            f"   Approval: {'Required' if self.requires_approval else 'Auto'}",
        ]
        for op in self.operations:
            lines.append(f"   {op.order+1}. [{op.priority.value}] {op.description or op.operation_name}")
        return "\n".join(lines)
